version: '3.8'

services:
  # ------------------------- [추가] Redis 서비스 -------------------------
  redis:
    image: "redis:alpine"
    container_name: suri_redis
    ports:
      - "6379:6379"
    restart: always
  # --------------------------------------------------------------------

  api-gateway:
    build:
      context: ./api-gateway
    container_name: suri_api_gateway
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - dialogue-service
      - strategy-service
      - rag-service
      - search-agent-service

  dialogue-service:
    build:
      context: ./dialogue-service
    container_name: suri_dialogue_service
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    restart: always

  strategy-service:
    build:
      context: ./strategy-service
    container_name: suri_strategy_service
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    restart: always
    # --- [추가] strategy-service가 시작되기 전에 redis가 먼저 실행되도록 설정 ---
    depends_on:
      - redis
    # --------------------------------------------------------------------

  rag-service:
    build:
      context: ./rag-service
    container_name: suri_rag_service
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    restart: always

  search-agent-service:
    build:
      context: ./search-agent-service
    container_name: suri_search_agent_service
    ports:
      - "8004:8004"
    restart: always