# version: '3.8' # 이 줄은 삭제하거나 주석 처리해도 됩니다.

services:
  redis:
    image: "redis:alpine"
    container_name: suri_redis
    ports:
      - "6379:6379"
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: suri_api_gateway
    ports:
      - "8000:8000"
    restart: always
    volumes: # --- [추가] ---
      - ./shared:/app/shared
    depends_on:
      - dialogue-service
      - strategy-service
      - rag-service
      - search-agent-service

  dialogue-service:
    build:
      context: ./dialogue-service
    container_name: suri_dialogue_service
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    restart: always
    volumes: # --- [추가] ---
      - ./shared:/app/shared

  strategy-service:
    build:
      context: ./strategy-service
    container_name: suri_strategy_service
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    restart: always
    volumes: # --- [추가] ---
      - ./shared:/app/shared
    depends_on:
      - redis

  rag-service:
    build:
      context: ./rag-service
    container_name: suri_rag_service
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    restart: always
    volumes: # --- [추가] ---
      - ./shared:/app/shared

  search-agent-service:
    build:
      context: ./search-agent-service
    container_name: suri_search_agent_service
    ports:
      - "8004:8004"
    restart: always
    volumes: # --- [추가] ---
      - ./shared:/app/shared